pipeline {
    agent none

    // Adds timestamps to console logs
    options {
        timestamps()
    }

    stages {
        stage('Update production configuration') {
            // Prepare a release branch of Spack for deployment by:
            //
            // 1. Updating the tracked branch
            // 2. Updating our internal Spack repository
            // 3. Copying the latest configuration files in place
            //

            agent {
                label 'fidis-login'
            }

            environment {
                SPACK_CHECKOUT_DIR = "/ssoft/spack/humagne/spack.v1"
                SPACK_SCITAS_REPOSITORY = "/ssoft/spack/humagne/scitas-repository"
                SENV_VIRTUALENV_PATH = "/home/scitasbuild/humagne/virtualenv/senv-py27"
            }

            steps {
                // Checkout Spack
                dir("${SPACK_CHECKOUT_DIR}") {
                    git url: "https://github.com/epfl-scitas/spack.git", branch: "releases/humagne"
                }

                // Checkout our internal repository
                dir("${SPACK_SCITAS_REPOSITORY}") {
                    git url: "https://github.com/epfl-scitas/spack-repo-externals.git", branch: "master"
                }

                // Update the command line tool we use in production
                // and configuration files
                sh  'jenkins/deploy/scripts/update_production_configuration.sh'
            }
        }

        stage('Prepare production stack') {
            // Ensure that all the compilers that are needed in
            // production are in place.
            //
            // 1. Compute which compilers are needed using a
            //    python command
            // 2. Check if they are installed, and if not install them
            //

            environment {
                SPACK_CHECKOUT_DIR = "/ssoft/spack/humagne/spack.v1"
                SENV_VIRTUALENV_PATH = "/home/scitasbuild/humagne/virtualenv/senv-py27"
            }

            parallel {
                stage('x86_E5v4_Mellanox') {
                    agent {
                        label 'x86_E5v4_Mellanox.rh74.slurm1711'
                    }
                    steps {
                        sh  'jenkins/deploy/scripts/install_production_compilers.sh'
                        sh  'jenkins/deploy/scripts/install_production_stack.sh'
                    }
                    post {
                        always {
                            archiveArtifacts artifacts:'*.txt, *.xml'
                            junit testResults:'*.xml', allowEmptyResults:true
                        }
                    }
                }
                stage('x86_S6g1_Mellanox') {
                    agent {
                        label 'x86_S6g1_Mellanox.rh74.slurm1711'
                    }
                    steps {
                        sh  'jenkins/deploy/scripts/install_production_compilers.sh'
                        sh  'jenkins/deploy/scripts/install_production_stack.sh'
                    }
                    post {
                        always {
                            archiveArtifacts artifacts:'*.txt, *.xml'
                            junit testResults:'*.xml', allowEmptyResults:true
                        }
                    }
                }
            }
        }

        stage('Populate mirror') {
            // Compute what needs to be installed in production (software that
            // is part of the planned environment, but not installed yet). Then
            // retrieve all the resources (tarballs, etc.) that are needed
            // to build it in a mirror.

            // TODO: the agent below must have access to the network
            agent {
                label 'fidis-login'
            }

            environment {
                SPACK_CHECKOUT_DIR = "/ssoft/spack/humagne/spack.v1"
                SENV_VIRTUALENV_PATH = "/home/scitasbuild/humagne/virtualenv/senv-py27"
            }

            steps {
                sh 'jenkins/deploy/scripts/populate_mirror.sh'
                stash name:'x86_E5v4_Mellanox', includes: 'to_be_installed.x86_E5v4_Mellanox.txt'
                stash name:'x86_S6g1_Mellanox', includes: 'to_be_installed.x86_S6g1_Mellanox.txt'
            }
            post {
                always {
                    archiveArtifacts artifacts:'*.txt, *.yaml'
                }
            }

        }

        stage('Deploy software') {
            // Deploy the software that is planned to be in the environment,
            // but not yet installed. Notify failures.

            environment {
                SPACK_CHECKOUT_DIR = "/ssoft/spack/humagne/spack.v1"
                SENV_VIRTUALENV_PATH = "/home/scitasbuild/humagne/virtualenv/senv-py27"
            }

            parallel {
                stage('x86_E5v4_Mellanox') {
                    agent {
                        label 'x86_E5v4_Mellanox.rh74.slurm1711'
                    }

                    steps {
                        unstash name: 'x86_E5v4_Mellanox'
                        sh 'jenkins/deploy/scripts/deploy_in_production.sh'
                        echo 'Notify failures somewhere'
                    }

                    post {
                        always {
                            archiveArtifacts artifacts:'*.txt, *.xml'
                            junit testResults:'*.xml', allowEmptyResults:true
                        }
                    }
                }

                stage('x86_S6g1_Mellanox') {
                    agent {
                        label 'x86_S6g1_Mellanox.rh74.slurm1711'
                    }

                    steps {
                        unstash name: 'x86_S6g1_Mellanox'
                        sh 'jenkins/deploy/scripts/deploy_in_production.sh'
                        echo 'Notify failures somewhere'
                    }

                    post {
                        always {
                            archiveArtifacts artifacts:'*.txt, *.xml'
                            junit testResults:'*.xml', allowEmptyResults: true
                        }
                    }
                }
            }
        }
    }
}
